* 1차 단항 피처들의 값이 [x1,x2]  = [0 1] 일 경우
* 2차 다항 피처들의 값은 [1, x1 = 0 , x2 = 1, x1*x2 =0 , x1^2 = 0, x2^2 =1] 로 [1,0,1,0,0,1] 6개로 늘려줌

In [1]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

#다항식으로 변환한 단항식 생성, [[0,1],[2,3]]의 2*2 행렬 생성
X= np.arange(4).reshape(2,2)

print('일차 단항식 계수 features :\n ',X)

일차 단항식 계수 features :
  [[0 1]
 [2 3]]


In [2]:
#degree = 2 인 2차 다항식으로 변환하기 위해 PolynomialFeatures를 이용하여 변환
poly = PolynomialFeatures(degree= 2)
poly.fit(X)
poly_ftr = poly.transform(X)
print('변환된 2차 다항식 계수 feature:\n', poly_ftr)

변환된 2차 다항식 계수 feature:
 [[1. 0. 1. 0. 0. 1.]
 [1. 2. 3. 4. 6. 9.]]


In [5]:
#Linear Regreesion에 3차 다항식 계수feature와 3차 다항식 결정값으로 학습 후 회귀계수 확인
from sklearn.linear_model import LinearRegression

def polynomial_func(X):
    y = 1+ 2*X + X**2+ X**3
    return y

X =  np.arange(4).reshape(2,2)
print('일차 단항식 계수 feature: \n',X)
y = polynomial_func(X)
print('삼차 다항식 결정값: \n',y)

poly_ftr = PolynomialFeatures(degree = 3).fit_transform(X)
print('3차 다항식 계수 feature: \n', poly_ftr)

#Linear Regreesion에 3차 다항식 계수 feature와 3차 다항식 결정값으로 학습 후 회귀계수 확인
model = LinearRegression()
model.fit(poly_ftr , y)

print('Polynomial 회귀계수 \n', np.round(model.coef_,2))
print('Polynomial 회귀 shape :', model.coef_.shape)

일차 단항식 계수 feature: 
 [[0 1]
 [2 3]]
삼차 다항식 결정값: 
 [[ 1  5]
 [17 43]]
3차 다항식 계수 feature: 
 [[ 1.  0.  1.  0.  0.  1.  0.  0.  0.  1.]
 [ 1.  2.  3.  4.  6.  9.  8. 12. 18. 27.]]
Polynomial 회귀계수 
 [[0.   0.02 0.02 0.05 0.07 0.1  0.1  0.14 0.22 0.31]
 [0.   0.06 0.06 0.11 0.17 0.23 0.23 0.34 0.51 0.74]]
Polynomial 회귀 shape : (2, 10)


In [7]:
#파이프라인 이용 다항 회귀

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

def polynomail_func(X):
    y = 1 + 2*X + X**2 + X**3
    return y

#pipeline객체로 streamline하게 Polynomial Feature변환과 Linear Regression을 연결
model = Pipeline([('Poly', PolynomialFeatures(degree = 3)),
                    ('linear', LinearRegression())])

x = np.arange(4).reshape(2,2)
y = polynomail_func(X)

model = model.fit(X,y)
print('Polynomial  회귀 계수\n', np.round(model.named_steps['linear'].coef_, 2))e

Polynomial  회귀 계수
 [[0.   0.02 0.02 0.05 0.07 0.1  0.1  0.14 0.22 0.31]
 [0.   0.06 0.06 0.11 0.17 0.23 0.23 0.34 0.51 0.74]]
