### 데이터 전처리 : sklearn.preprocessing.LabelEncoder
##### class sklearn.preprocessing.LabelEncoder (이거는 매개변수가 없음)
순서 : fit -> transform

In [1]:
from sklearn.preprocessing import LabelEncoder

items = ['냉장고','전자레인지','컴퓨터','선풍기','티비','선풍기','믹서','믹서']
encoder = LabelEncoder() #클래스 부르는것 처럼

encoder.fit(items)
labels = encoder.transform(items)

print('인코딩 변환값:', labels)
print('인코딩 클래스:', encoder.classes_) #encodr.classes_ : 디코딩 하는 역할
print('인코딩 변환값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

인코딩 변환값: [0 3 4 2 5 2 1 1]
인코딩 클래스: ['냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터' '티비']
인코딩 변환값: ['컴퓨터' '티비' '선풍기' '냉장고' '믹서' '믹서' '전자레인지' '전자레인지']


### sklearn.preprocessing.OneHotEncoder
##### class sklearn.preprocessing.OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error')

In [16]:
from sklearn.preprocessing import OneHotEncoder
items = ['냉장고','전자레인지','컴퓨터','선풍기','티비','선풍기','믹서','믹서']

#원핫인코딩을 하기 위해 따라해봄 sckitlearn페이지

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
#labels  #1차원
bels=labels.reshape(-1,1) #2차원으로 변경

oh_encoder = OneHotEncoder()
oh_encoder.fit(bels)
oh_encoder.transform(bels).toarray()


print('인코딩 변환값:', labels)
print('인코딩 클래스:', encoder.classes_) #encodr.classes_ : 디코딩 하는 역할
print('인코딩 변환값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]])

In [14]:
labels

array([0, 3, 4, 2, 5, 2, 1, 1])

In [13]:
bels

array([[0],
       [3],
       [4],
       [2],
       [5],
       [2],
       [1],
       [1]])